import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* Header */}
        <div className={styles.headContainer}>
          <div className={styles.siteIdent}>
            <Image src="/ident.png" alt="ident" width={45} height={45} />
            <h2 className={styles.identText}>Brunel Tech</h2>
          </div>

          <div className={styles.navContainer}>
            {/*Create a nav list that contains Home, About, Blog and Society.
              When hovering over Society, produce a dropdown with more options*/}

            <ul className={styles.navList}>
              <li className={styles.navItem}>
                <a href="#" className={styles.navLink}>
                  Home
                </a>
              </li>
              <li className={styles.navItem}>
                <a href="#" className={styles.navLink}>
                  About
                </a>
              </li>
              <li className={styles.navItem}>
                <a href="#" className={styles.navLink}>
                  Blog
                </a>
              </li>
              <li className={styles.navItem}>
                <a href="#" className={styles.navLink}>
                  Society
                </a>
              </li>
            </ul>

            <div className={styles.societyDropdown}>
              <ul className={styles.societyDropdownList}>
                <li className={styles.societyDropdownItem}>
                  <a href="#" className={styles.societyDropdownLink}>
                    What's On
                  </a>
                </li>
                <li className={styles.societyDropdownItem}>
                  <a href="#" className={styles.societyDropdownLink}>
                    Join Us
                  </a>
                </li>
                <li className={styles.societyDropdownItem}>
                  <a href="#" className={styles.societyDropdownLink}>
                    Test
                  </a>
                </li>
              </ul>
            </div>

          </div>
        </div>
      </main>
    </div>
  )
}
